#1. Calculate the total revenue generated by two product categories in a store
#importing the Numpy library
import numpy as np
#Initializing the arr
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])
#Using sum() function to sum two array
total_revenue = np.sum(category1_revenue) + np.sum(category2_revenue)
print("Total revenue:", total_revenue)


